sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest PHP_APCU=enabled
    - php: 7.0
      env: WP_VERSION=latest PHP_APCU=enabled
    - php: 5.6
      env: WP_VERSION=latest PHP_APCU=disabled
    - php: 5.6
      env: WP_VERSION=nightly PHP_APCU=enabled
    - php: 5.6
      env: WP_TRAVISCI=phpcs

before_script:
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        if [[ "$PHP_APCU" == "enabled" ]] ; then
          if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
            echo "no" | pecl install channel://pecl.php.net/apcu-5.1.5
          else
            echo "no\nno" | pecl install channel://pecl.php.net/apcu-4.0.11
          fi
          echo "apc.enable_cli='on'" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        fi
      fi
    - |
      if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
        composer global require "phpunit/phpunit=5.6.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
      fi
    - composer install
    - |
      if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
        npm install
      fi

script:
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        phpunit
        phpunit -c multisite.xml
      fi
    - |
      if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
        grunt phpcs
      fi
